<% 
Option Explicit

Dim strDate, strMonth, strDay, strYear, strMinute, strHour

strDate = Now()

strMonth = Month(strDate)
strDay = Day(strDate)
strYear = Year(strDate)
strMinute = Minute(strDate)
strHour = Hour(strDate)

If Len(strMinute) = 1 Then 
	strMinute = "0" & strMinute
End If
If Len(strHour) = 1 Then 
	strHour = "0" & strHour
End If

Response.Write "// file automatically generated by http://www.teamwarfare.com for BigBrown's Tribes 2 Reservation mod " & vbCrLf
Response.Write "$CurrentWebTime[24] = """ & strHour & ":" & strMinute & """;" & vbCrLf
Response.Write "$WebMinute = """ & strMinute & """;" & vbCrLf
Response.Write "$CurrentDate = """ & strDay & " " & MonthName(strMonth, 1) & " " & strYear & """;" & vbCrLF
%>