function fMyTWLLoggedIn(strName) {
	fMakeMenu(arrParents, 'my_twl','',strName,'default.asp')
	fMakeMenu(arrMyTWL, 'my_twl','',strName,'default.asp')
			fMakeMenu(arrMyTWL, 'home','my_twl','Home', 'default.asp')
			fMakeMenu(arrMyTWL, 'account','my_twl','Account Maintenance')
			fMakeMenu(arrMyTWL, 'profile','account','Profile','viewplayer.asp?player=' + escape(strName))
			fMakeMenu(arrMyTWL, 'edit_profile','account','Edit Profile','addplayer.asp?IsEdit=true')
			fMakeMenu(arrMyTWL, 'register_team','account','Register Team','addteam.asp')
			fMakeMenu(arrMyTWL, 'logout','account','Logout', '', 'fPopLogin();')
			fMakeMenu(arrMyTWL, 'preferences','account','Preferences','preferences.asp')
			fMakeMenu(arrMyTWL, 'requestnamechange','account','Request Name Change','request/ReqNameChange.asp?player=' + escape(strName))
	
		fMakeMenu(arrMyTWL, 'news_archive','my_twl','News Archive','newsarchive.asp')
		fMakeMenu(arrMyTWL, 'search','my_twl','Search','')
			fMakeMenu(arrMyTWL, 'search1','search','Find Player By Name','searchPlayerByName.asp')
			fMakeMenu(arrMyTWL, 'search4','search','Find Player By In Game Identifier','searchPlayerByIdentifier.asp')
			fMakeMenu(arrMyTWL, 'search2','search','Find Team By Name','searchTeamByName.asp')
			fMakeMenu(arrMyTWL, 'search3','search','Find Team By Tag','searchTeamByTag.asp')
		
		fMakeMenu(arrMyTWL, 'myteams','my_twl','My Teams')

}

function fMyTWL() {
	fMakeMenu(arrParents, 'my_twl','','my twl', 'default.asp')
		fMakeMenu(arrMyTWL, 'my_twl','','my twl', 'default.asp')
		fMakeMenu(arrMyTWL, 'home','my_twl','Home', 'default.asp')
		fMakeMenu(arrMyTWL, 'login','my_twl','Login', '', 'fPopLogin();')
		fMakeMenu(arrMyTWL, 'forgot_password','my_twl','Forgot Password','forgotpassword.asp')
		fMakeMenu(arrMyTWL, 'activate','my_twl','Deactivated Account?','activate.asp')
		fMakeMenu(arrMyTWL, 'register','my_twl','Register','addplayer.asp')
		fMakeMenu(arrMyTWL, 'contactus','my_twl','Contact Us','staff.asp')
}

function fOperations() {				
	fMakeMenu(arrParents, 'oper','','operations')
		fMakeMenu(arrOperations, 'oper','','operations')
		fMakeMenu(arrOperations, 'files','oper','Downloads / Files','files')
		fMakeMenu(arrOperations, 'stuff','oper','TWL Stuff Store','stuff/')
		fMakeMenu(arrOperations, 'staff','oper','Contact Us / Staff','staff.asp')
		fMakeMenu(arrOperations, 'winners','oper','Prize Winners','winners.asp')
	
		fMakeMenu(arrOperations, 'demos','oper','Demo Library', 'demos')
		fMakeMenu(arrOperations, 'Voting','oper','Voting Booth', 'ballot/')
		fMakeMenu(arrOperations, 'Contrib','oper','TWL Contributors', 'contributors.asp')
}	function fForumsAll() { 
		fMakeMenu(arrParents, 'dbm552','','forums','forums/')
		fMakeMenu(arrForums, 'dbm552','','forums','forums/')
		fMakeMenu(arrForums, 'dbm616','dbm552','Forum Index','forums/')
		fMakeMenu(arrForums, 'dbm554','dbm552','General Forums','forums/forumdisplay.asp?ForumID=9')
		fMakeMenu(arrForums, 'dbm555','dbm552','Site Support &amp; Member Services','forums/forumdisplay.asp?ForumID=19')
		fMakeMenu(arrForums, 'dbm556','dbm552','Recruiting','forums/forumdisplay.asp?ForumID=11')
		fMakeMenu(arrForums, 'dbm557','dbm552','Game Specific','forums/default.asp#Category1')
			fMakeMenu(arrForums, 'dbm560','dbm557','America\'s Army','')
				fMakeMenu(arrForums, 'dbm561','dbm560','AA Ladder Forums','forums/forumdisplay.asp?forumid=25')
				fMakeMenu(arrForums, 'dbm1205','dbm560','AA 1v1 Servers','forums/forumdisplay.asp?forumid=211')
				fMakeMenu(arrForums, 'dbm981','dbm560','AA League Forums','forums/forumdisplay.asp?forumid=160')
				fMakeMenu(arrForums, 'dbm983','dbm560','CDC Support','forums/forumdisplay.asp?forumid=54')
				fMakeMenu(arrForums, 'dbm859','dbm560','Leadership Forum','forums/forumdisplay.asp?forumid=132')
				fMakeMenu(arrForums, 'dbm1185','dbm560','Q &amp; A','forums/forumdisplay.asp?forumid=206')
			fMakeMenu(arrForums, 'dbm1709','dbm557','Area 51','forums/forumdisplay.asp?forumid=341')
			fMakeMenu(arrForums, 'dbm564','dbm557','Battlefield 1942','')
				fMakeMenu(arrForums, 'dbm615','dbm564','Battlefield 1942','forums/forumdisplay.asp?ForumID=27')
				fMakeMenu(arrForums, 'dbm889','dbm564','Battlefield 1942: Capture the Flag','forums/forumdisplay.asp?forumid=136')
				fMakeMenu(arrForums, 'dbm565','dbm564','Battlefield 1942: Desert Combat','forums/forumdisplay.asp?ForumID=101')
				fMakeMenu(arrForums, 'dbm1108','dbm564','Battlefield 1942: Leadership Forum','forums/forumdisplay.asp?forumid=180')
			fMakeMenu(arrForums, 'dbm1653','dbm557','Battlefield 2','')
				fMakeMenu(arrForums, 'dbm1555','dbm1653','Battlefield 2 Ladders','forums/forumdisplay.asp?ForumID=291')
				fMakeMenu(arrForums, 'dbm1654','dbm1653','Battlefield 2 Leagues','forums/forumdisplay.asp?ForumID=323')
			fMakeMenu(arrForums, 'dbm1684','dbm557','Battlefield: Vietnam','')
				fMakeMenu(arrForums, 'dbm1086','dbm1684','Battlefield: Vietnam','forums/forumdisplay.asp?forumid=172')
				fMakeMenu(arrForums, 'dbm1273','dbm1684','Battlefield: Vietnam Leadership Forum ','forums/forumdisplay.asp?forumid=227')
			fMakeMenu(arrForums, 'dbm1238','dbm557','Brothers in Arms','forums/forumdisplay.asp?forumid=218')
			fMakeMenu(arrForums, 'dbm640','dbm557','Call of Duty','')
				fMakeMenu(arrForums, 'dbm1597','dbm640','CoD European Ladder Forums','forums/forumdisplay.asp?forumid=302')
				fMakeMenu(arrForums, 'dbm862','dbm640','CoD Ladder Forums','forums/forumdisplay.asp?forumid=107')
				fMakeMenu(arrForums, 'dbm863','dbm640','CoD League Forums','forums/forumdisplay.asp?forumid=133')
				fMakeMenu(arrForums, 'dbm1372','dbm640','CoD: UO Ladders','forums/forumdisplay.asp?forumid=239')
				fMakeMenu(arrForums, 'dbm1373','dbm640','CoD: UO Leagues','forums/forumdisplay.asp?forumid=245')
			fMakeMenu(arrForums, 'dbm1712','dbm557','Call of Duty 2','')
				fMakeMenu(arrForums, 'dbm1713','dbm1712','COD 2: Ladder','forums/forumdisplay.asp?forumid=343')
			fMakeMenu(arrForums, 'dbm571','dbm557','Counter-Strike','')
				fMakeMenu(arrForums, 'dbm1434','dbm571','Counter-Strike','forums/forumdisplay.asp?ForumID=14')
				fMakeMenu(arrForums, 'dbm1435','dbm571','Counter-Strike:Source Ladders','forums/forumdisplay.asp?ForumID=269')
				fMakeMenu(arrForums, 'dbm1633','dbm571','Counter-Strike:Source Leadership','forums/forumdisplay.asp?ForumID=318')
				fMakeMenu(arrForums, 'dbm1690','dbm571','Counter-Strike:Source Leagues','forums/forumdisplay.asp?ForumID=335')
			fMakeMenu(arrForums, 'dbm851','dbm557','Day of Defeat','forums/forumdisplay.asp?ForumID=58')
			fMakeMenu(arrForums, 'dbm1158','dbm557','Enemy Territory','')
				fMakeMenu(arrForums, 'dbm659','dbm1158','Enemy Territory','forums/forumdisplay.asp?ForumID=40')
				fMakeMenu(arrForums, 'dbm1159','dbm1158','Enemy Territory Alphas','forums/forumdisplay.asp?forumid=195')
				fMakeMenu(arrForums, 'dbm1525','dbm1158','Enemy Territory Fortress','forums/forumdisplay.asp?ForumID=283')
			fMakeMenu(arrForums, 'dbm1695','dbm557','F.E.A.R. First Encounter Assault Recon','forums/forumdisplay.asp?forumid=338')
			fMakeMenu(arrForums, 'dbm1235','dbm557','Ghost Recon','forums/forumdisplay.asp?ForumID=24')
			fMakeMenu(arrForums, 'dbm1346','dbm557','Half-Life&#178;','forums/forumdisplay.asp?forumid=155')
			fMakeMenu(arrForums, 'dbm641','dbm557','Halo','')
				fMakeMenu(arrForums, 'dbm1005','dbm641','Halo Ladders','forums/forumdisplay.asp?forumid=108')
				fMakeMenu(arrForums, 'dbm1006','dbm641','Halo Leagues','forums/forumdisplay.asp?forumid=161')
			fMakeMenu(arrForums, 'dbm1155','dbm557','Joint Operations','forums/forumdisplay.asp?forumid=193')
			fMakeMenu(arrForums, 'dbm1528','dbm557','LOTR - Battle for Middle Earth','forums/forumdisplay.asp?forumid=284')
			fMakeMenu(arrForums, 'dbm1359','dbm557','Madden 2005','forums/forumdisplay.asp?forumid=242')
			fMakeMenu(arrForums, 'dbm578','dbm557','Medal of Honor','')
				fMakeMenu(arrForums, 'dbm580','dbm578','Allied Assault','forums/forumdisplay.asp?ForumID=13')
				fMakeMenu(arrForums, 'dbm1590','dbm578','Breakthrough','forums/forumdisplay.asp?forumid=110')
				fMakeMenu(arrForums, 'dbm1591','dbm578','Spearhead','forums/forumdisplay.asp?forumid=37')
			fMakeMenu(arrForums, 'dbm1646','dbm557','Pariah','forums/forumdisplay.asp?forumid=320')
			fMakeMenu(arrForums, 'dbm1626','dbm557','Quake 2','forums/forumdisplay.asp?forumid=312')
			fMakeMenu(arrForums, 'dbm690','dbm557','Quake 3 ','')
				fMakeMenu(arrForums, 'dbm1413','dbm690','Excessive','forums/forumdisplay.asp?forumid=260')
				fMakeMenu(arrForums, 'dbm593','dbm690','Urban Terror','forums/forumdisplay.asp?ForumID=32')
			fMakeMenu(arrForums, 'dbm823','dbm557','Rainbow Six 3','')
				fMakeMenu(arrForums, 'dbm583','dbm823','Rainbow Six 3: Raven Shield/Athena Sword','forums/forumdisplay.asp?ForumID=34')
				fMakeMenu(arrForums, 'dbm1126','dbm823','Raven Shield Leadership Forum','forums/forumdisplay.asp?forumid=186')
				fMakeMenu(arrForums, 'dbm825','dbm823','Raven Shield League','forums/forumdisplay.asp?forumid=127')
			fMakeMenu(arrForums, 'dbm567','dbm557','Return to Castle Wolfenstein','')
				fMakeMenu(arrForums, 'dbm568','dbm567','Castle Wolfenstein','forums/forumdisplay.asp?ForumID=12')
				fMakeMenu(arrForums, 'dbm570','dbm567','Shrub','forums/forumdisplay.asp?ForumID=52')
			fMakeMenu(arrForums, 'dbm1389','dbm557','Rome: Total War','forums/forumdisplay.asp?forumid=252')
			fMakeMenu(arrForums, 'dbm613','dbm557','Soldier of Fortune 2','forums/forumdisplay.asp?forumid=23')
			fMakeMenu(arrForums, 'dbm1630','dbm557','Splinter Cell Chaos Theory','forums/forumdisplay.asp?forumid=316')
			fMakeMenu(arrForums, 'dbm1493','dbm557','SWAT 4','forums/forumdisplay.asp?forumid=281')
			fMakeMenu(arrForums, 'dbm587','dbm557','Tribes','forums/forumdisplay.asp?ForumID=1')
			fMakeMenu(arrForums, 'dbm588','dbm557','Tribes 2','')
				fMakeMenu(arrForums, 'dbm589','dbm588','Tribes 2 - CTF, etc...','forums/forumdisplay.asp?ForumID=4')
				fMakeMenu(arrForums, 'dbm590','dbm588','Tribes 2 Base','forums/forumdisplay.asp?ForumID=53')
			fMakeMenu(arrForums, 'dbm1128','dbm557','Tribes: Vengeance','')
				fMakeMenu(arrForums, 'dbm1348','dbm1128','T:V General','forums/forumdisplay.asp?forumid=182')
				fMakeMenu(arrForums, 'dbm1349','dbm1128','T:V Recruiting','forums/forumdisplay.asp?forumid=240')
			fMakeMenu(arrForums, 'dbm1439','dbm557','Unreal Tournament 1999','forums/forumdisplay.asp?forumid=167')
			fMakeMenu(arrForums, 'dbm769','dbm557','Unreal Tournament 2004','')
				fMakeMenu(arrForums, 'dbm1168','dbm769','UT2004 Ladders','forums/forumdisplay.asp?ForumID=124')
				fMakeMenu(arrForums, 'dbm1170','dbm769','UT2004 Leagues','forums/forumdisplay.asp?forumid=202')
			fMakeMenu(arrForums, 'dbm1521','dbm557','UTXMP','forums/forumdisplay.asp?forumid=282')
			fMakeMenu(arrForums, 'dbm612','dbm557','Warcraft 3','forums/forumdisplay.asp?ForumID=26')
			fMakeMenu(arrForums, 'dbm1397','dbm557','Warhammer 40k: Dawn of War','forums/forumdisplay.asp?forumid=255')
		fMakeMenu(arrForums, 'dbm559','dbm552','PlayStation 2','')
			fMakeMenu(arrForums, 'dbm598','dbm559','General PS2 Online','forums/forumdisplay.asp?forumid=87')
			fMakeMenu(arrForums, 'dbm1648','dbm559','SOCOM II','forums/forumdisplay.asp?forumid=321')
			fMakeMenu(arrForums, 'dbm599','dbm559','Tribes: Aerial Assault','forums/forumdisplay.asp?forumid=86')
			fMakeMenu(arrForums, 'dbm600','dbm559','Tribes: Aerial Assault Scheduling','forums/forumdisplay.asp?forumid=89')
		fMakeMenu(arrForums, 'dbm558','dbm552','Xbox Live','')
			fMakeMenu(arrForums, 'dbm1059','dbm558','Counter Strike','forums/forumdisplay.asp?forumid=164')
			fMakeMenu(arrForums, 'dbm594','dbm558','General Xbox Live','forums/forumdisplay.asp?forumid=57')
			fMakeMenu(arrForums, 'dbm1568','dbm558','Ghost Recon 2','forums/forumdisplay.asp?forumid=56 ')
			fMakeMenu(arrForums, 'dbm1474','dbm558','Halo 2 Ladders','forums/forumdisplay.asp?forumid=275')
			fMakeMenu(arrForums, 'dbm1566','dbm558','Halo 2 Leagues','forums/forumdisplay.asp?forumid=296')
			fMakeMenu(arrForums, 'dbm1058','dbm558','Rainbow Six 3','forums/forumdisplay.asp?forumid=145')
			fMakeMenu(arrForums, 'dbm1625','dbm558','Splintercell Chaos Theory ','forums/forumdisplay.asp?forumid=311')
		fMakeMenu(arrForums, 'dbm689','dbm552','News &amp; Reviews','forums/forumdisplay.asp?ForumID=117')
		fMakeMenu(arrForums, 'dbm871','dbm552','Tournaments','forums/forumdisplay.asp?ForumID=135')
			fMakeMenu(arrForums, 'dbm1696','dbm871','Battlefield 2 - Global Crisis 2005','forums/forumdisplay.asp?forumid=334')
		fMakeMenu(arrForums, 'dbm874','dbm552','TWL Hosting Support','forums/forumdisplay.asp?forumid=128')
	}
	function fForumsStaff() { 
		fMakeMenu(arrForums, 'dbm553','dbm552','Staff Forums','') 
		fMakeMenu(arrForums, 'dbm601','dbm553','TWL Staff','forums/forumdisplay.asp?ForumID=3')
		fMakeMenu(arrForums, 'dbm606','dbm553','Business and Marketing','')
			fMakeMenu(arrForums, 'dbm1615','dbm606','General Business and Marketing','forums/forumdisplay.asp?ForumID=22')
			fMakeMenu(arrForums, 'dbm1524','dbm606','Sponsorship','forums/forumdisplay.asp?forumid=181')
		fMakeMenu(arrForums, 'dbm1121','dbm553','Competition Managers','forums/forumdisplay.asp?forumid=184')
		fMakeMenu(arrForums, 'dbm653','dbm553','News Staff','forums/forumdisplay.asp?forumid=111')
		fMakeMenu(arrForums, 'dbm1618','dbm553','News Submissions','forums/forumdisplay.asp?forumid=297')
		fMakeMenu(arrForums, 'dbm1593','dbm553','Shoutcasting','')
			fMakeMenu(arrForums, 'dbm1701','dbm1593','BFRadio.com','forums/forumdisplay.asp?forumid=340')
			fMakeMenu(arrForums, 'dbm1596','dbm1593','Radio ITG','forums/forumdisplay.asp?forumid=214')
			fMakeMenu(arrForums, 'dbm1594','dbm1593','TSN Central','forums/forumdisplay.asp?forumid=150')
		fMakeMenu(arrForums, 'dbm1482','dbm553','Staff World of Warcraft','forums/forumdisplay.asp?forumid=280')
		fMakeMenu(arrForums, 'dbm1144','dbm553','TeamWarfare Development','forums/forumdisplay.asp?forumid=5')
	} 
	function fForumsStaff2() { 
		fMakeMenu(arrForums, 'dbm963','dbm552','Staff Gaming Forums','') 
		fMakeMenu(arrForums, 'dbm984','dbm963','America\'s Army','')
			fMakeMenu(arrForums, 'dbm1545','dbm984','AA Cheat Team','forums/forumdisplay.asp?forumid=286')
			fMakeMenu(arrForums, 'dbm1099','dbm984','AA Cheating','forums/forumdisplay.asp?forumid=174')
			fMakeMenu(arrForums, 'dbm1265','dbm984','AA General Staff','forums/forumdisplay.asp?forumid=225')
			fMakeMenu(arrForums, 'dbm988','dbm984','AA League Staff','forums/forumdisplay.asp?forumid=159')
			fMakeMenu(arrForums, 'dbm1054','dbm984','AA Match Observers','forums/forumdisplay.asp?forumid=162')
			fMakeMenu(arrForums, 'dbm1291','dbm984','AA Moderators','forums/forumdisplay.asp?forumid=228')
			fMakeMenu(arrForums, 'dbm1241','dbm984','AA Watch List','forums/forumdisplay.asp?forumid=219')
			fMakeMenu(arrForums, 'dbm989','dbm984','Match Disputes','forums/forumdisplay.asp?forumid=60')
		fMakeMenu(arrForums, 'dbm1071','dbm963','Battlefield','')
			fMakeMenu(arrForums, 'dbm1659','dbm1071','Battlefield 2 Development','forums/forumdisplay.asp?forumid=325')
			fMakeMenu(arrForums, 'dbm1661','dbm1071','Battlefield 2 Discussion','forums/forumdisplay.asp?forumid=326')
			fMakeMenu(arrForums, 'dbm1672','dbm1071','Battlefield 2 EU Administration','forums/forumdisplay.asp?forumid=328')
			fMakeMenu(arrForums, 'dbm1479','dbm1071','Battlefield Administration','forums/forumdisplay.asp?forumid=278')
			fMakeMenu(arrForums, 'dbm1480','dbm1071','Battlefield AntiCheat','forums/forumdisplay.asp?forumid=279')
			fMakeMenu(arrForums, 'dbm1203','dbm1071','BF:V Match Disputes','forums/forumdisplay.asp?forumid=199')
			fMakeMenu(arrForums, 'dbm1662','dbm1071','BF2 Match Disputes','forums/forumdisplay.asp?forumid=324')
			fMakeMenu(arrForums, 'dbm1072','dbm1071','BF42 Match Disputes','forums/forumdisplay.asp?forumid=61')
		fMakeMenu(arrForums, 'dbm1645','dbm963','Brothers in Arms','')
			fMakeMenu(arrForums, 'dbm1677','dbm1645','General Admin','forums/forumdisplay.asp?forumid=310')
			fMakeMenu(arrForums, 'dbm1678','dbm1645','Match Disputes','forums/forumdisplay.asp?forumid=329')
		fMakeMenu(arrForums, 'dbm846','dbm963','Call of Duty','')
			fMakeMenu(arrForums, 'dbm1412','dbm846',' CoD Admin News','forums/forumdisplay.asp?forumid=259')
			fMakeMenu(arrForums, 'dbm1049','dbm846',' General Admin','forums/forumdisplay.asp?forumid=130')
			fMakeMenu(arrForums, 'dbm1619','dbm846',' General Euro Admin','forums/forumdisplay.asp?forumid=307')
			fMakeMenu(arrForums, 'dbm968','dbm846',' Ladder Admin','forums/forumdisplay.asp?forumid=153')
			fMakeMenu(arrForums, 'dbm966','dbm846',' League Admin','forums/forumdisplay.asp?forumid=152')
			fMakeMenu(arrForums, 'dbm1694','dbm846','CoD 2 Admin','forums/forumdisplay.asp?forumid=337')
			fMakeMenu(arrForums, 'dbm1563','dbm846','CoD OC Private Forums','forums/forumdisplay.asp?forumid=295')
			fMakeMenu(arrForums, 'dbm1237','dbm846','CoD: Cheating','forums/forumdisplay.asp?forumid=215')
			fMakeMenu(arrForums, 'dbm1675','dbm846','CoD: TWL &amp; CAL Cheating','forums/forumdisplay.asp?forumid=294')
			fMakeMenu(arrForums, 'dbm980','dbm846','Match Disputes','forums/forumdisplay.asp?forumid=125')
		fMakeMenu(arrForums, 'dbm1313','dbm963','Counter-Strike','')
			fMakeMenu(arrForums, 'dbm1679','dbm1313','General Admin','forums/forumdisplay.asp?forumid=231')
			fMakeMenu(arrForums, 'dbm1680','dbm1313','Match Disputes','forums/forumdisplay.asp?forumid=72')
		fMakeMenu(arrForums, 'dbm1468','dbm963','Counter-Strike:Source','')
			fMakeMenu(arrForums, 'dbm1629','dbm1468','Counter-Strike:Source Anti-Cheat','forums/forumdisplay.asp?forumid=315')
			fMakeMenu(arrForums, 'dbm1620','dbm1468','Counter-Strike:Source EU Administration','forums/forumdisplay.asp?forumid=308')
			fMakeMenu(arrForums, 'dbm1676','dbm1468','Counter-Strike:Source EU MO','forums/forumdisplay.asp?forumid=330')
			fMakeMenu(arrForums, 'dbm1469','dbm1468','Counter-Strike:Source NA Ladders','forums/forumdisplay.asp?forumid=272')
			fMakeMenu(arrForums, 'dbm1710','dbm1468','Counter-Strike:Source NA Leagues','forums/forumdisplay.asp?forumid=342')
			fMakeMenu(arrForums, 'dbm1515','dbm1468','Match Disputes','forums/forumdisplay.asp?forumid=273')
		fMakeMenu(arrForums, 'dbm854','dbm963','Day Of Defeat','forums/forumdisplay.asp?ForumID=131')
		fMakeMenu(arrForums, 'dbm924','dbm963','Ghost Recon','')
			fMakeMenu(arrForums, 'dbm1187','dbm924','General Admin','forums/forumdisplay.asp?forumid=143')
			fMakeMenu(arrForums, 'dbm1186','dbm924','Ghost Recon Anti-Cheat Team','forums/forumdisplay.asp?forumid=187')
			fMakeMenu(arrForums, 'dbm1283','dbm924','Match Disputes','forums/forumdisplay.asp?forumid=76')
		fMakeMenu(arrForums, 'dbm991','dbm963','Half-Life 2','forums/forumdisplay.asp?forumid=156')
		fMakeMenu(arrForums, 'dbm758','dbm963','HALO','')
			fMakeMenu(arrForums, 'dbm1285','dbm758','General Admin','forums/forumdisplay.asp?forumid=121')
			fMakeMenu(arrForums, 'dbm1284','dbm758','Match Disputes','forums/forumdisplay.asp?forumid=122')
		fMakeMenu(arrForums, 'dbm1269','dbm963','Joint Operations','')
			fMakeMenu(arrForums, 'dbm1279','dbm1269','General Admin','forums/forumdisplay.asp?forumid=226')
			fMakeMenu(arrForums, 'dbm1280','dbm1269','Match Disputes','forums/forumdisplay.asp?forumid=192')
		fMakeMenu(arrForums, 'dbm1571','dbm963','LOTR: Battle for Middle Earth','')
			fMakeMenu(arrForums, 'dbm1572','dbm1571','General Admin','forums/forumdisplay.asp?forumid=300')
			fMakeMenu(arrForums, 'dbm1573','dbm1571','Match Disputes','forums/forumdisplay.asp?forumid=285')
		fMakeMenu(arrForums, 'dbm631','dbm963','Medal of Honor','')
			fMakeMenu(arrForums, 'dbm1122','dbm631','General Admin','forums/forumdisplay.asp?forumid=106')
			fMakeMenu(arrForums, 'dbm1281','dbm631','Match Disputes - MOHAA','forums/forumdisplay.asp?forumid=64')
			fMakeMenu(arrForums, 'dbm1601','dbm631','Match Disputes - SH/BT','forums/forumdisplay.asp?forumid=123')
		fMakeMenu(arrForums, 'dbm1638','dbm963','PS2 Admin','forums/forumdisplay.asp?forumid=317')
		fMakeMenu(arrForums, 'dbm614','dbm963','Rainbow Six 3','forums/forumdisplay.asp?forumid=102')
			fMakeMenu(arrForums, 'dbm1604','dbm614','Future Projects Discussion','forums/forumdisplay.asp?forumid=306')
			fMakeMenu(arrForums, 'dbm970','dbm614','Ladder Admin','forums/forumdisplay.asp?forumid=102')
			fMakeMenu(arrForums, 'dbm1125','dbm614','Leadership Forum','forums/forumdisplay.asp?forumid=186')
			fMakeMenu(arrForums, 'dbm971','dbm614','League Admin','forums/forumdisplay.asp?forumid=154')
			fMakeMenu(arrForums, 'dbm972','dbm614','Match Disputes','forums/forumdisplay.asp?forumid=66')
		fMakeMenu(arrForums, 'dbm1714','dbm963','Rome:Total War','forums/forumdisplay.asp?forumid=345')
			fMakeMenu(arrForums, 'dbm1715','dbm1714','Admin','forums/forumdisplay.asp?forumid=345')
			fMakeMenu(arrForums, 'dbm1716','dbm1714','Match Disputes ','forums/forumdisplay.asp?forumid=344')
		fMakeMenu(arrForums, 'dbm655','dbm963','RTCW/Enemy Territory','')
			fMakeMenu(arrForums, 'dbm1274','dbm655','Admin ','forums/forumdisplay.asp?forumid=113')
			fMakeMenu(arrForums, 'dbm1642','dbm655','Anti-Cheat','forums/forumdisplay.asp?forumid=319')
			fMakeMenu(arrForums, 'dbm1277','dbm655','Disputes - ET','forums/forumdisplay.asp?forumid=116')
			fMakeMenu(arrForums, 'dbm1275','dbm655','Disputes - RTCW','forums/forumdisplay.asp?forumid=70')
			fMakeMenu(arrForums, 'dbm1599','dbm655','ETF Staff','forums/forumdisplay.asp?forumid=304')
		fMakeMenu(arrForums, 'dbm1444','dbm963','Soldier of Fortune 2 ','')
			fMakeMenu(arrForums, 'dbm1445','dbm1444','General Admin','forums/forumdisplay.asp?forumid=115')
			fMakeMenu(arrForums, 'dbm1446','dbm1444','Match Disputes','forums/forumdisplay.asp?forumid=73')
		fMakeMenu(arrForums, 'dbm1551','dbm963','SWAT 4','forums/forumdisplay.asp?forumid=288')
			fMakeMenu(arrForums, 'dbm1553','dbm1551','Ladder Admin','forums/forumdisplay.asp?forumid=288')
			fMakeMenu(arrForums, 'dbm1554','dbm1551','Match Disputes ','forums/forumdisplay.asp?forumid=289')
		fMakeMenu(arrForums, 'dbm1106','dbm963','Tribes 2','')
			fMakeMenu(arrForums, 'dbm1682','dbm1106','Match Disputes','forums/forumdisplay.asp?forumid=59')
			fMakeMenu(arrForums, 'dbm1681','dbm1106','Tribes 2 Cheating','forums/forumdisplay.asp?forumid=45')
			fMakeMenu(arrForums, 'dbm921','dbm1106','Tribes 2 DRB','forums/forumdisplay.asp?forumid=141')
		fMakeMenu(arrForums, 'dbm1341','dbm963','Tribes Vengeance','')
			fMakeMenu(arrForums, 'dbm1683','dbm1341','Match Disputes','forums/forumdisplay.asp?forumid=233')
			fMakeMenu(arrForums, 'dbm1418','dbm1341','T:V Demo Review','forums/forumdisplay.asp?forumid=263')
			fMakeMenu(arrForums, 'dbm1419','dbm1341','T:V Map Council','forums/forumdisplay.asp?forumid=262')
			fMakeMenu(arrForums, 'dbm1420','dbm1341','T:V Rules and Exploits','forums/forumdisplay.asp?forumid=264')
			fMakeMenu(arrForums, 'dbm1340','dbm1341','Tribes Vengeance Staff','forums/forumdisplay.asp?forumid=183')
		fMakeMenu(arrForums, 'dbm1105','dbm963','Unreal Tournament 2004','')
			fMakeMenu(arrForums, 'dbm1152','dbm1105','General Admin','forums/forumdisplay.asp?forumid=179')
			fMakeMenu(arrForums, 'dbm1151','dbm1105','Match Disputes','forums/forumdisplay.asp?forumid=177')
		fMakeMenu(arrForums, 'dbm1441','dbm963','Unreal Tournament 99','')
			fMakeMenu(arrForums, 'dbm1442','dbm1441','General Admin','forums/forumdisplay.asp?forumid=270')
			fMakeMenu(arrForums, 'dbm1443','dbm1441','Match Disputes','forums/forumdisplay.asp?forumid=168')
		fMakeMenu(arrForums, 'dbm1102','dbm963','Urban Terror','')
			fMakeMenu(arrForums, 'dbm1308','dbm1102','Admin','forums/forumdisplay.asp?forumid=176')
			fMakeMenu(arrForums, 'dbm1306','dbm1102','Match Disputes','forums/forumdisplay.asp?forumid=68')
		fMakeMenu(arrForums, 'dbm1579','dbm963','Xbox -  Admin','forums/forumdisplay.asp?forumid=301')
		fMakeMenu(arrForums, 'dbm1639','dbm963','Xbox - Halo 2','')
			fMakeMenu(arrForums, 'dbm1640','dbm1639','General Admin','forums/forumdisplay.asp?forumid=309')
			fMakeMenu(arrForums, 'dbm1641','dbm1639','Match Disputes - Halo 2','forums/forumdisplay.asp?forumid=276')
	} 
	function fCompetition() { 
	fMakeMenu(arrParents, 'dbm1','','competition','ladderlist.asp') 
	fMakeMenu(arrComp, 'dbm1','','competition','ladderlist.asp') 
	}	
	function fRules() { 
		fMakeMenu(arrParents, 'dbm2','','rules','rulechooser.asp')
		fMakeMenu(arrRules, 'dbm2','','rules','rulechooser.asp')
	} 
