function fMyTWLLoggedIn(strName) {
	fMakeMenu(arrParents, 'my_twl','',strName,'default.asp')
	fMakeMenu(arrMyTWL, 'my_twl','',strName,'default.asp')
			fMakeMenu(arrMyTWL, 'home','my_twl','Home', 'default.asp')
			fMakeMenu(arrMyTWL, 'account','my_twl','Account Maintenance')
			fMakeMenu(arrMyTWL, 'profile','account','Profile','viewplayer.asp?player=' + escape(strName))
			fMakeMenu(arrMyTWL, 'edit_profile','account','Edit Profile','addplayer.asp?IsEdit=true')
			fMakeMenu(arrMyTWL, 'register_team','account','Register Team','addteam.asp')
			fMakeMenu(arrMyTWL, 'logout','account','Logout', '', 'fPopLogin();')
			fMakeMenu(arrMyTWL, 'preferences','account','Preferences','preferences.asp')
			fMakeMenu(arrMyTWL, 'requestnamechange','account','Request Name Change','request/ReqNameChange.asp?player=' + escape(strName))
	
		fMakeMenu(arrMyTWL, 'news_archive','my_twl','News Archive','newsarchive.asp')
		fMakeMenu(arrMyTWL, 'search','my_twl','Search','')
			fMakeMenu(arrMyTWL, 'search1','search','Find Player By Name','searchPlayerByName.asp')
			fMakeMenu(arrMyTWL, 'search4','search','Find Player By In Game Identifier','searchPlayerByIdentifier.asp')
			fMakeMenu(arrMyTWL, 'search2','search','Find Team By Name','searchTeamByName.asp')
			fMakeMenu(arrMyTWL, 'search3','search','Find Team By Tag','searchTeamByTag.asp')
		
		fMakeMenu(arrMyTWL, 'myteams','my_twl','My Teams')

}

function fMyTWL() {
	fMakeMenu(arrParents, 'my_twl','','my twl', 'default.asp')
		fMakeMenu(arrMyTWL, 'my_twl','','my twl', 'default.asp')
		fMakeMenu(arrMyTWL, 'home','my_twl','Home', 'default.asp')
		fMakeMenu(arrMyTWL, 'login','my_twl','Login', '', 'fPopLogin();')
		fMakeMenu(arrMyTWL, 'forgot_password','my_twl','Forgot Password','forgotpassword.asp')
		fMakeMenu(arrMyTWL, 'activate','my_twl','Deactivated Account?','activate.asp')
		fMakeMenu(arrMyTWL, 'register','my_twl','Register','addplayer.asp')
		fMakeMenu(arrMyTWL, 'contactus','my_twl','Contact Us','staff.asp')
}

function fOperations() {				
	fMakeMenu(arrParents, 'oper','','operations')
		fMakeMenu(arrOperations, 'oper','','operations')
		fMakeMenu(arrOperations, 'files','oper','Downloads / Files','files')
		fMakeMenu(arrOperations, 'stuff','oper','TWL Stuff Store','stuff/')
		fMakeMenu(arrOperations, 'staff','oper','Contact Us / Staff','staff.asp')
		fMakeMenu(arrOperations, 'winners','oper','Prize Winners','winners.asp')
	
		fMakeMenu(arrOperations, 'demos','oper','Demo Library', 'demos')
		fMakeMenu(arrOperations, 'Voting','oper','Voting Booth', 'ballot/')
		fMakeMenu(arrOperations, 'Contrib','oper','TWL Contributors', 'contributors.asp')
}	function fForumsAll() { 
		fMakeMenu(arrParents, 'dbm552','','forums','forums/')
		fMakeMenu(arrForums, 'dbm552','','forums','forums/')
		fMakeMenu(arrForums, 'dbm616','dbm552','Forum Index','forums/')
		fMakeMenu(arrForums, 'dbm555','dbm552','Site Support &amp; Member Services','forums/forumdisplay.asp?ForumID=19')
		fMakeMenu(arrForums, 'dbm556','dbm552','Recruiting','forums/forumdisplay.asp?ForumID=11')
		fMakeMenu(arrForums, 'dbm557','dbm552','PC Game Specific','forums/default.asp#Category1')
			fMakeMenu(arrForums, 'dbm560','dbm557','AA - America\'s Army','')
				fMakeMenu(arrForums, 'dbm561','dbm560','AA Ladder Forums','forums/forumdisplay.asp?forumid=25')
				fMakeMenu(arrForums, 'dbm981','dbm560','AA League Forums EU','forums/forumdisplay.asp?forumid=160')
				fMakeMenu(arrForums, 'dbm1920','dbm560','AA League Forums NA','forums/forumdisplay.asp?forumid=388')
				fMakeMenu(arrForums, 'dbm983','dbm560','CDC Support','forums/forumdisplay.asp?forumid=54')
				fMakeMenu(arrForums, 'dbm859','dbm560','Leadership Forum','forums/forumdisplay.asp?forumid=132')
				fMakeMenu(arrForums, 'dbm1185','dbm560','Q &amp; A','forums/forumdisplay.asp?forumid=206')
			fMakeMenu(arrForums, 'dbm1879','dbm557','Age of Empires III ','forums/forumdisplay.asp?forumid=372')
			fMakeMenu(arrForums, 'dbm564','dbm557','Battlefield 1942','forums/forumdisplay.asp?ForumID=27')
			fMakeMenu(arrForums, 'dbm1653','dbm557','Battlefield 2','')
				fMakeMenu(arrForums, 'dbm1890','dbm1653','Battlefield 2 Ladders EU','forums/forumdisplay.asp?forumid=374')
				fMakeMenu(arrForums, 'dbm1741','dbm1653','Battlefield 2 Leadership Forum','forums/forumdisplay.asp?forumid=20')
				fMakeMenu(arrForums, 'dbm1555','dbm1653','Battlefield 2: Ladders NA','forums/forumdisplay.asp?ForumID=291')
				fMakeMenu(arrForums, 'dbm1654','dbm1653','Battlefield 2: Leagues','forums/forumdisplay.asp?Forumid=323')
			fMakeMenu(arrForums, 'dbm1684','dbm557','Battlefield: Vietnam','forums/forumdisplay.asp?forumid=172')
			fMakeMenu(arrForums, 'dbm640','dbm557','Call of Duty','')
				fMakeMenu(arrForums, 'dbm862','dbm640','Call of Duty','forums/forumdisplay.asp?forumid=107')
				fMakeMenu(arrForums, 'dbm1372','dbm640','Call of Duty: United Offensive','forums/forumdisplay.asp?forumid=239')
			fMakeMenu(arrForums, 'dbm1712','dbm557','Call of Duty 2','')
				fMakeMenu(arrForums, 'dbm1713','dbm1712','CoD 2 NA: Ladder','forums/forumdisplay.asp?forumid=343')
				fMakeMenu(arrForums, 'dbm1862','dbm1712','CoD 2 NA: League','forums/forumdisplay.asp?forumid=368')
				fMakeMenu(arrForums, 'dbm1876','dbm1712','CoD 2: EU Discussion','forums/forumdisplay.asp?forumid=302')
				fMakeMenu(arrForums, 'dbm1869','dbm1712','CoD 2: Leadership','forums/forumdisplay.asp?forumid=201')
			fMakeMenu(arrForums, 'dbm571','dbm557','Counter-Strike - 1.6 &amp; Source','')
				fMakeMenu(arrForums, 'dbm1434','dbm571','Counter-Strike 1.6','forums/forumdisplay.asp?ForumID=14')
				fMakeMenu(arrForums, 'dbm1435','dbm571','Counter-Strike: Source Ladders','forums/forumdisplay.asp?ForumID=269')
				fMakeMenu(arrForums, 'dbm1633','dbm571','Counter-Strike: Source Leadership','forums/forumdisplay.asp?ForumID=318')
				fMakeMenu(arrForums, 'dbm1690','dbm571','Counter-Strike: Source Leagues','forums/forumdisplay.asp?ForumID=335')
				fMakeMenu(arrForums, 'dbm1847','dbm571','Counter-Strike: Source Zblock Support','forums/forumdisplay.asp?ForumID=367')
			fMakeMenu(arrForums, 'dbm851','dbm557','Day of Defeat: Source','forums/forumdisplay.asp?ForumID=58')
			fMakeMenu(arrForums, 'dbm1794','dbm557','EA Sports','')
				fMakeMenu(arrForums, 'dbm1359','dbm1794','EA Sports General Discussion','forums/forumdisplay.asp?forumid=357')
				fMakeMenu(arrForums, 'dbm1759','dbm1794','Madden 2006','forums/forumdisplay.asp?forumid=148')
			fMakeMenu(arrForums, 'dbm1158','dbm557','Enemy Territory','')
				fMakeMenu(arrForums, 'dbm659','dbm1158','Enemy Territory','forums/forumdisplay.asp?ForumID=40')
				fMakeMenu(arrForums, 'dbm1159','dbm1158','Enemy Territory Alphas','forums/forumdisplay.asp?forumid=195')
				fMakeMenu(arrForums, 'dbm1775','dbm1158','Quake Wars','forums/forumdisplay.asp?forumid=355')
			fMakeMenu(arrForums, 'dbm1695','dbm557','F.E.A.R.','forums/forumdisplay.asp?forumid=338')
			fMakeMenu(arrForums, 'dbm1904','dbm557','Ghost Recon Series','')
				fMakeMenu(arrForums, 'dbm1235','dbm1904','Ghost Recon','forums/forumdisplay.asp?ForumID=24')
				fMakeMenu(arrForums, 'dbm1905','dbm1904','Ghost Recon: Advanced Warfighter','forums/forumdisplay.asp?ForumID=375')
			fMakeMenu(arrForums, 'dbm1771','dbm557','Quake','')
				fMakeMenu(arrForums, 'dbm593','dbm1771','Quake 3: Urban Terror','forums/forumdisplay.asp?ForumID=32')
				fMakeMenu(arrForums, 'dbm1770','dbm1771','Quake 4','forums/forumdisplay.asp?forumid=354')
			fMakeMenu(arrForums, 'dbm823','dbm557','Rainbow Six 3: Raven Shield','')
				fMakeMenu(arrForums, 'dbm583','dbm823','Raven Shield Ladder','forums/forumdisplay.asp?ForumID=34')
				fMakeMenu(arrForums, 'dbm1126','dbm823','Raven Shield Leadership Forum','forums/forumdisplay.asp?forumid=186')
				fMakeMenu(arrForums, 'dbm825','dbm823','Raven Shield League','forums/forumdisplay.asp?forumid=127')
			fMakeMenu(arrForums, 'dbm1873','dbm557','Red Orchestra ','forums/forumdisplay.asp?forumid=82')
			fMakeMenu(arrForums, 'dbm567','dbm557','Return to Castle Wolfenstein','')
				fMakeMenu(arrForums, 'dbm568','dbm567','Castle Wolfenstein','forums/forumdisplay.asp?ForumID=12')
				fMakeMenu(arrForums, 'dbm570','dbm567','Shrub','forums/forumdisplay.asp?ForumID=52')
			fMakeMenu(arrForums, 'dbm1389','dbm557','Rome: Total War','forums/forumdisplay.asp?forumid=252')
			fMakeMenu(arrForums, 'dbm587','dbm557','Tribes','forums/forumdisplay.asp?ForumID=1')
			fMakeMenu(arrForums, 'dbm588','dbm557','Tribes 2','')
				fMakeMenu(arrForums, 'dbm589','dbm588','Tribes 2 - CTF, etc...','forums/forumdisplay.asp?ForumID=4')
				fMakeMenu(arrForums, 'dbm590','dbm588','Tribes 2 Base','forums/forumdisplay.asp?ForumID=53')
			fMakeMenu(arrForums, 'dbm1128','dbm557','Tribes: Vengeance','forums/forumdisplay.asp?forumid=182')
				fMakeMenu(arrForums, 'dbm1924','dbm1128','T:V LT Tournament','forums/forumdisplay.asp?forumid=390')
			fMakeMenu(arrForums, 'dbm769','dbm557','Unreal Tournament','')
				fMakeMenu(arrForums, 'dbm1439','dbm769','UT1999','forums/forumdisplay.asp?forumid=167')
				fMakeMenu(arrForums, 'dbm1168','dbm769','UT2004 Ladders','forums/forumdisplay.asp?ForumID=124')
				fMakeMenu(arrForums, 'dbm1170','dbm769','UT2004 Leagues','forums/forumdisplay.asp?forumid=202')
			fMakeMenu(arrForums, 'dbm612','dbm557','Warcraft 3','')
				fMakeMenu(arrForums, 'dbm1872','dbm612','Warcraft 3','forums/forumdisplay.asp?ForumID=26')
				fMakeMenu(arrForums, 'dbm1824','dbm612','Warcraft 3: DOTA','forums/forumdisplay.asp?ForumID=362')
			fMakeMenu(arrForums, 'dbm1397','dbm557','Warhammer 40k: Dawn of War','forums/forumdisplay.asp?forumid=255')
		fMakeMenu(arrForums, 'dbm559','dbm552','PlayStation','')
			fMakeMenu(arrForums, 'dbm598','dbm559','General Discussion','forums/forumdisplay.asp?forumid=87')
			fMakeMenu(arrForums, 'dbm1937','dbm559','PS2: Battlefield2: Modern Combat Ladders','forums/forumdisplay.asp?forumid=394')
			fMakeMenu(arrForums, 'dbm1936','dbm559','PS2: Socom 3 Ladders','forums/forumdisplay.asp?forumid=393')
			fMakeMenu(arrForums, 'dbm1938','dbm559','PS2: Star Wars Battlefront 1 Ladders','forums/forumdisplay.asp?forumid=395')
			fMakeMenu(arrForums, 'dbm1939','dbm559','PS2: Star Wars Battlefront 2 Ladders','forums/forumdisplay.asp?forumid=396')
		fMakeMenu(arrForums, 'dbm558','dbm552','Xbox Live','')
			fMakeMenu(arrForums, 'dbm1804','dbm558','General Discussion','forums/forumdisplay.asp?forumid=359')
			fMakeMenu(arrForums, 'dbm1916','dbm558','Ghost Recon Advanced Warfighter Ladders','forums/forumdisplay.asp?forumid=381')
			fMakeMenu(arrForums, 'dbm1474','dbm558','Halo 2 Ladders','forums/forumdisplay.asp?forumid=275')
			fMakeMenu(arrForums, 'dbm1566','dbm558','Perfect Dark Zero Ladders ','forums/forumdisplay.asp?forumid=376')
		fMakeMenu(arrForums, 'dbm1948','dbm552','General','forums/forumdisplay.asp?forumid=9')
		fMakeMenu(arrForums, 'dbm689','dbm552','News &amp; Reviews','forums/forumdisplay.asp?ForumID=117')
		fMakeMenu(arrForums, 'dbm871','dbm552','Tournaments','')
			fMakeMenu(arrForums, 'dbm1888','dbm871','No Tournaments at present..','')
		fMakeMenu(arrForums, 'dbm874','dbm552','TWL Hosting by Trinity Gaming','forums/forumdisplay.asp?forumid=128')
	}
	function fForumsStaff() { 
		fMakeMenu(arrForums, 'dbm553','dbm552','Staff Forums','') 
		fMakeMenu(arrForums, 'dbm601','dbm553','TWL Staff','forums/forumdisplay.asp?ForumID=3')
		fMakeMenu(arrForums, 'dbm1121','dbm553','Competition Managers','forums/forumdisplay.asp?forumid=184')
		fMakeMenu(arrForums, 'dbm606','dbm553','Marketing &amp; Sponsorship','')
			fMakeMenu(arrForums, 'dbm1912','dbm606',' Marketing Admin','forums/forumdisplay.asp?forumid=380')
			fMakeMenu(arrForums, 'dbm1917','dbm606','EU Sponsorship Focus','forums/forumdisplay.asp?forumid=387')
			fMakeMenu(arrForums, 'dbm1913','dbm606','NA Sponsorship Focus','forums/forumdisplay.asp?forumid=181')
		fMakeMenu(arrForums, 'dbm1867','dbm553','News Team','')
			fMakeMenu(arrForums, 'dbm1868','dbm1867','News Admin','forums/forumdisplay.asp?forumid=292')
			fMakeMenu(arrForums, 'dbm653','dbm1867','News Staff','forums/forumdisplay.asp?forumid=111')
			fMakeMenu(arrForums, 'dbm1618','dbm1867','News Submissions','forums/forumdisplay.asp?forumid=297')
		fMakeMenu(arrForums, 'dbm1942','dbm553','Quality Control','')
			fMakeMenu(arrForums, 'dbm1945','dbm1942','Moved Threads','forums/forumdisplay.asp?forumid=44')
			fMakeMenu(arrForums, 'dbm1943','dbm1942','Staff','forums/forumdisplay.asp?forumid=398')
		fMakeMenu(arrForums, 'dbm1593','dbm553','Shoutcasting','')
			fMakeMenu(arrForums, 'dbm1701','dbm1593','Electronic Gaming Live Network','forums/forumdisplay.asp?forumid=340')
			fMakeMenu(arrForums, 'dbm1596','dbm1593','Radio ITG','forums/forumdisplay.asp?forumid=214')
			fMakeMenu(arrForums, 'dbm1594','dbm1593','TsN Central','forums/forumdisplay.asp?forumid=150')
		fMakeMenu(arrForums, 'dbm1482','dbm553','Staff World of Warcraft','forums/forumdisplay.asp?forumid=280')
	} 
	function fForumsStaff2() { 
		fMakeMenu(arrForums, 'dbm963','dbm552','Staff Gaming Forums','') 
		fMakeMenu(arrForums, 'dbm1897','dbm963','Age of Empires III','')
			fMakeMenu(arrForums, 'dbm1898','dbm1897','General Admin','forums/forumdisplay.asp?forumid=266')
			fMakeMenu(arrForums, 'dbm1900','dbm1897','Match Disputes','forums/forumdisplay.asp?forumid=151')
		fMakeMenu(arrForums, 'dbm984','dbm963','America\'s Army','')
			fMakeMenu(arrForums, 'dbm1545','dbm984','AA Anti-Cheat Team','forums/forumdisplay.asp?forumid=286')
			fMakeMenu(arrForums, 'dbm1099','dbm984','AA Cheating','forums/forumdisplay.asp?forumid=174')
			fMakeMenu(arrForums, 'dbm1910','dbm984','AA EU Staff','forums/forumdisplay.asp?forumid=377')
			fMakeMenu(arrForums, 'dbm1265','dbm984','AA General Staff','forums/forumdisplay.asp?forumid=225')
			fMakeMenu(arrForums, 'dbm1923','dbm984','AA League Staff EU','forums/forumdisplay.asp?forumid=389')
			fMakeMenu(arrForums, 'dbm988','dbm984','AA League Staff NA','forums/forumdisplay.asp?forumid=159')
			fMakeMenu(arrForums, 'dbm1054','dbm984','AA Match Observers','forums/forumdisplay.asp?forumid=162')
			fMakeMenu(arrForums, 'dbm1949','dbm984','AA NA Staff','forums/forumdisplay.asp?forumid=399')
			fMakeMenu(arrForums, 'dbm1241','dbm984','AA Watch List','forums/forumdisplay.asp?forumid=219')
			fMakeMenu(arrForums, 'dbm1866','dbm984','America\'s Army Event','forums/forumdisplay.asp?forumid=369')
			fMakeMenu(arrForums, 'dbm989','dbm984','Match Disputes','forums/forumdisplay.asp?forumid=60')
		fMakeMenu(arrForums, 'dbm1071','dbm963','Battlefield','')
			fMakeMenu(arrForums, 'dbm1672','dbm1071','Battlefield    EU Administration','forums/forumdisplay.asp?forumid=328')
			fMakeMenu(arrForums, 'dbm1479','dbm1071','Battlefield    NA Administration','forums/forumdisplay.asp?forumid=278')
			fMakeMenu(arrForums, 'dbm1480','dbm1071','Battlefield   Anti-Cheat','forums/forumdisplay.asp?forumid=279')
			fMakeMenu(arrForums, 'dbm1072','dbm1071','BF 1942 Match Disputes','forums/forumdisplay.asp?forumid=61')
			fMakeMenu(arrForums, 'dbm1203','dbm1071','BF:V Match Disputes','forums/forumdisplay.asp?forumid=199')
			fMakeMenu(arrForums, 'dbm1662','dbm1071','BF2 Match Disputes','forums/forumdisplay.asp?forumid=324')
		fMakeMenu(arrForums, 'dbm846','dbm963','Call of Duty','')
			fMakeMenu(arrForums, 'dbm1619','dbm846','CoD:   EU Administration','forums/forumdisplay.asp?forumid=307')
			fMakeMenu(arrForums, 'dbm1049','dbm846','CoD:   NA Administration','forums/forumdisplay.asp?forumid=130')
			fMakeMenu(arrForums, 'dbm1563','dbm846','CoD:  Observer Corp','forums/forumdisplay.asp?forumid=295')
			fMakeMenu(arrForums, 'dbm1237','dbm846','CoD: Anti-Cheat','forums/forumdisplay.asp?forumid=215')
			fMakeMenu(arrForums, 'dbm980','dbm846','Match Disputes','forums/forumdisplay.asp?forumid=125')
		fMakeMenu(arrForums, 'dbm1821','dbm963','Call of Duty 2','')
			fMakeMenu(arrForums, 'dbm1826','dbm1821','CoD 2:   EU Administration','forums/forumdisplay.asp?forumid=307')
			fMakeMenu(arrForums, 'dbm1694','dbm1821','CoD 2:   NA Administration','forums/forumdisplay.asp?forumid=337')
			fMakeMenu(arrForums, 'dbm1901','dbm1821','CoD 2:  Event Forum','forums/forumdisplay.asp?forumid=294')
			fMakeMenu(arrForums, 'dbm1858','dbm1821','CoD 2:  Observer Corp','forums/forumdisplay.asp?forumid=295')
			fMakeMenu(arrForums, 'dbm1857','dbm1821','CoD 2: Anti-Cheat','forums/forumdisplay.asp?forumid=215')
			fMakeMenu(arrForums, 'dbm1783','dbm1821','Match Disputes','forums/forumdisplay.asp?forumid=200')
		fMakeMenu(arrForums, 'dbm1313','dbm963','Counter-Strike 1.6','')
			fMakeMenu(arrForums, 'dbm1679','dbm1313','Counter-Strike 1.6 NA Administration','forums/forumdisplay.asp?forumid=231')
			fMakeMenu(arrForums, 'dbm1680','dbm1313','Match Disputes','forums/forumdisplay.asp?forumid=72')
		fMakeMenu(arrForums, 'dbm1468','dbm963','Counter-Strike: Source','')
			fMakeMenu(arrForums, 'dbm1629','dbm1468','Counter-Strike: Source Anti-Cheat','forums/forumdisplay.asp?forumid=315')
			fMakeMenu(arrForums, 'dbm1620','dbm1468','Counter-Strike: Source EU Administration','forums/forumdisplay.asp?forumid=308')
			fMakeMenu(arrForums, 'dbm1469','dbm1468','Counter-Strike: Source NA Ladders','forums/forumdisplay.asp?forumid=272')
			fMakeMenu(arrForums, 'dbm1710','dbm1468','Counter-Strike: Source NA Leagues','forums/forumdisplay.asp?forumid=342')
			fMakeMenu(arrForums, 'dbm1515','dbm1468','Match Disputes','forums/forumdisplay.asp?forumid=273')
		fMakeMenu(arrForums, 'dbm854','dbm963','Day of Defeat: Source','')
			fMakeMenu(arrForums, 'dbm1788','dbm854','Day of Defeat: Source NA Administration','forums/forumdisplay.asp?ForumID=131')
			fMakeMenu(arrForums, 'dbm1790','dbm854','Match Disputes','forums/forumdisplay.asp?forumid=75')
		fMakeMenu(arrForums, 'dbm1773','dbm963','EA Sports','')
			fMakeMenu(arrForums, 'dbm1774','dbm1773','General Admin','forums/forumdisplay.asp?forumid=243')
			fMakeMenu(arrForums, 'dbm1798','dbm1773','Match Disputes ','forums/forumdisplay.asp?forumid=244')
		fMakeMenu(arrForums, 'dbm1735','dbm963','FEAR','')
			fMakeMenu(arrForums, 'dbm1791','dbm1735','General Admin','forums/forumdisplay.asp?forumid=339')
			fMakeMenu(arrForums, 'dbm1792','dbm1735','Match Disputes','forums/forumdisplay.asp?forumid=49')
		fMakeMenu(arrForums, 'dbm924','dbm963','Ghost Recon','')
			fMakeMenu(arrForums, 'dbm1187','dbm924','Ghost Recon Administration','forums/forumdisplay.asp?forumid=143')
			fMakeMenu(arrForums, 'dbm1186','dbm924','Ghost Recon Anti-Cheat','forums/forumdisplay.asp?forumid=187')
			fMakeMenu(arrForums, 'dbm1283','dbm924','Match Disputes','forums/forumdisplay.asp?forumid=76')
		fMakeMenu(arrForums, 'dbm1638','dbm963','PS2','')
			fMakeMenu(arrForums, 'dbm1779','dbm1638','General Admin','forums/forumdisplay.asp?forumid=317')
			fMakeMenu(arrForums, 'dbm1902','dbm1638','Match Disputes','forums/forumdisplay.asp?forumid=327')
		fMakeMenu(arrForums, 'dbm1737','dbm963','Quake 4','')
			fMakeMenu(arrForums, 'dbm1814','dbm1737','General Admin','forums/forumdisplay.asp?forumid=360')
			fMakeMenu(arrForums, 'dbm1815','dbm1737','Match Disputes','forums/forumdisplay.asp?forumid=251')
		fMakeMenu(arrForums, 'dbm614','dbm963','Rainbow Six 3: RavenShield','')
			fMakeMenu(arrForums, 'dbm970','dbm614','Ladder Admin','forums/forumdisplay.asp?forumid=102')
			fMakeMenu(arrForums, 'dbm1125','dbm614','Leadership Forum','forums/forumdisplay.asp?forumid=186')
			fMakeMenu(arrForums, 'dbm971','dbm614','League Admin','forums/forumdisplay.asp?forumid=154')
			fMakeMenu(arrForums, 'dbm972','dbm614','Match Disputes','forums/forumdisplay.asp?forumid=66')
		fMakeMenu(arrForums, 'dbm1885','dbm963','Red Orchestra','')
			fMakeMenu(arrForums, 'dbm1886','dbm1885','  General Admin','forums/forumdisplay.asp?forumid=373')
			fMakeMenu(arrForums, 'dbm1887','dbm1885','  Red Orchestra Development','forums/forumdisplay.asp?forumid=325')
			fMakeMenu(arrForums, 'dbm1903','dbm1885','Match Disputes','forums/forumdisplay.asp?forumid=88')
		fMakeMenu(arrForums, 'dbm1714','dbm963','Rome:Total War','')
			fMakeMenu(arrForums, 'dbm1715','dbm1714','General Admin','forums/forumdisplay.asp?forumid=345')
			fMakeMenu(arrForums, 'dbm1716','dbm1714','Match Disputes ','forums/forumdisplay.asp?forumid=344')
		fMakeMenu(arrForums, 'dbm655','dbm963','RTCW/Enemy Territory','')
			fMakeMenu(arrForums, 'dbm1274','dbm655','Admin ','forums/forumdisplay.asp?forumid=113')
			fMakeMenu(arrForums, 'dbm1642','dbm655','Anti-Cheat','forums/forumdisplay.asp?forumid=319')
			fMakeMenu(arrForums, 'dbm1277','dbm655','Match Disputes - ET','forums/forumdisplay.asp?forumid=116')
			fMakeMenu(arrForums, 'dbm1275','dbm655','Match Disputes - RTCW','forums/forumdisplay.asp?forumid=70')
		fMakeMenu(arrForums, 'dbm1341','dbm963','Tribes','')
			fMakeMenu(arrForums, 'dbm1340','dbm1341',' Tribes   Administration','forums/forumdisplay.asp?forumid=183')
			fMakeMenu(arrForums, 'dbm1681','dbm1341',' Tribes 2 Anti-Cheat','forums/forumdisplay.asp?forumid=45')
			fMakeMenu(arrForums, 'dbm1682','dbm1341','Match Disputes -  T2','forums/forumdisplay.asp?forumid=59')
			fMakeMenu(arrForums, 'dbm1683','dbm1341','Match Disputes - T:V','forums/forumdisplay.asp?forumid=233')
		fMakeMenu(arrForums, 'dbm1105','dbm963','Unreal Tournament 2004','')
			fMakeMenu(arrForums, 'dbm1152','dbm1105','General Admin','forums/forumdisplay.asp?forumid=179')
			fMakeMenu(arrForums, 'dbm1151','dbm1105','Match Disputes','forums/forumdisplay.asp?forumid=177')
			fMakeMenu(arrForums, 'dbm1822','dbm1105','UT2004-99 Anti-Cheat','forums/forumdisplay.asp?forumid=361')
		fMakeMenu(arrForums, 'dbm1441','dbm963','Unreal Tournament 99','')
			fMakeMenu(arrForums, 'dbm1442','dbm1441','General Admin','forums/forumdisplay.asp?forumid=270')
			fMakeMenu(arrForums, 'dbm1443','dbm1441','Match Disputes','forums/forumdisplay.asp?forumid=168')
			fMakeMenu(arrForums, 'dbm1823','dbm1441','UT2004-99 Anti-Cheat','forums/forumdisplay.asp?forumid=361')
		fMakeMenu(arrForums, 'dbm1102','dbm963','Urban Terror','')
			fMakeMenu(arrForums, 'dbm1308','dbm1102','General Admin','forums/forumdisplay.asp?forumid=176')
			fMakeMenu(arrForums, 'dbm1306','dbm1102','Match Disputes','forums/forumdisplay.asp?forumid=68')
		fMakeMenu(arrForums, 'dbm1579','dbm963','Xbox','')
			fMakeMenu(arrForums, 'dbm1784','dbm1579','Match Disputes - Xbox360: GRAW ','forums/forumdisplay.asp?forumid=386')
			fMakeMenu(arrForums, 'dbm1785','dbm1579','Match Disputes - XBox360: Perfect Dark Zero','forums/forumdisplay.asp?forumid=165')
			fMakeMenu(arrForums, 'dbm1786','dbm1579','Xbox Administration ','forums/forumdisplay.asp?forumid=301')
		fMakeMenu(arrForums, 'dbm1639','dbm963','Xbox - Halo 2','')
			fMakeMenu(arrForums, 'dbm1640','dbm1639','General Admin','forums/forumdisplay.asp?forumid=309')
			fMakeMenu(arrForums, 'dbm1641','dbm1639','Match Disputes - Halo 2','forums/forumdisplay.asp?forumid=276')
	} 
	function fCompetition() { 
	fMakeMenu(arrParents, 'dbm1','','competition','ladderlist.asp') 
	fMakeMenu(arrComp, 'dbm1','','competition','ladderlist.asp') 
	}	
	function fRules() { 
		fMakeMenu(arrParents, 'dbm2','','rules','rulechooser.asp')
		fMakeMenu(arrRules, 'dbm2','','rules','rulechooser.asp')
	} 
